# New-SigningKey.ps1 — generate the update-signing ECDSA P-256 key pair (run ONCE).
#
#   Private key  -> scripts\.signing\ec_priv.b64      (base64 of D||X||Y, GITIGNORED — keep safe)
#   Public key   -> monitor_app\src\update_pubkey.h   (BCRYPT_ECCPUBLIC_BLOB, committed)
#
# The private key signs each release's version.json (New-VersionJson.ps1). The public
# key is embedded in monitor_app and verifies the manifest before applying an update.
# Re-running with -Force ROTATES the key — old signatures stop verifying, so every
# client must be rebuilt+reinstalled with the new public key. Don't rotate casually.
#
#   powershell -File scripts\New-SigningKey.ps1          # create (refuses if key exists)
#   powershell -File scripts\New-SigningKey.ps1 -Force   # rotate

[CmdletBinding()]
param([switch]$Force)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\lib\Common.ps1"

$root      = Get-RepoRoot
$signDir   = Join-Path $PSScriptRoot '.signing'
$privPath  = Join-Path $signDir 'ec_priv.b64'
$pubHeader = Join-Path $root 'monitor_app\src\update_pubkey.h'

if ((Test-Path $privPath) -and -not $Force) {
    throw "Private key already exists: $privPath`nUse -Force to ROTATE (invalidates all old signatures; every client must be rebuilt)."
}
New-Item -ItemType Directory -Force -Path $signDir | Out-Null

# Generate P-256 key pair.
$ec = [System.Security.Cryptography.ECDsa]::Create([System.Security.Cryptography.ECCurve+NamedCurves]::nistP256)
$p  = $ec.ExportParameters($true)   # D = private scalar, Q.X / Q.Y = public point
$D = $p.D; $X = $p.Q.X; $Y = $p.Q.Y
if ($D.Length -ne 32 -or $X.Length -ne 32 -or $Y.Length -ne 32) {
    throw "unexpected key component size (D=$($D.Length) X=$($X.Length) Y=$($Y.Length))"
}

# Private key file: base64( D || X || Y ), 96 raw bytes.
$priv = New-Object byte[] 96
[Array]::Copy($D, 0, $priv, 0,  32)
[Array]::Copy($X, 0, $priv, 32, 32)
[Array]::Copy($Y, 0, $priv, 64, 32)
[IO.File]::WriteAllText($privPath, [Convert]::ToBase64String($priv))

# Public header: BCRYPT_ECCPUBLIC_BLOB = magic + cbKey + X + Y  (8 + 32 + 32 = 72 bytes).
#   magic = BCRYPT_ECDSA_PUBLIC_P256_MAGIC = 0x31534345 ("ECS1"), little-endian bytes 45 43 53 31
#   cbKey = 32, little-endian 20 00 00 00
$blob = New-Object 'System.Collections.Generic.List[byte]'
$blob.AddRange([byte[]]@(0x45, 0x43, 0x53, 0x31))
$blob.AddRange([byte[]]@(0x20, 0x00, 0x00, 0x00))
$blob.AddRange($X)
$blob.AddRange($Y)
$bytes = $blob.ToArray()

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// AUTO-GENERATED by scripts\New-SigningKey.ps1 — do NOT edit by hand.')
[void]$sb.AppendLine('// ECDSA P-256 public key (BCRYPT_ECCPUBLIC_BLOB) for update-manifest verification.')
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine("static const unsigned char GAM_UPDATE_PUBKEY[$($bytes.Length)] = {")
for ($i = 0; $i -lt $bytes.Length; $i += 12) {
    $end = [Math]::Min($i + 11, $bytes.Length - 1)
    $row = ($bytes[$i..$end] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', '
    [void]$sb.AppendLine("    $row,")
}
[void]$sb.AppendLine('};')
[IO.File]::WriteAllText($pubHeader, $sb.ToString())

Write-Host "Private key  -> $privPath   (KEEP SAFE — gitignored)" -ForegroundColor Yellow
Write-Host "Public header -> $pubHeader   ($($bytes.Length) bytes)" -ForegroundColor Green
