// gen_assets.mjs — embed monitor_web/dist/** into a C++ header as byte arrays.
//
// Reads the built frontend and emits monitor_app/src/embedded_assets.h containing
// one `static const unsigned char aN[]` per file plus a lookup table. The prod
// build serves these from memory via WebResourceRequested, so the shipped exe is
// fully self-contained (no external dist/ folder).
//
// Run from build.cmd (cwd = monitor_app):  node tools\gen_assets.mjs
// Paths are resolved relative to THIS file, so cwd does not matter.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative, sep, extname } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))         // monitor_app/tools
const DIST = join(here, '..', '..', 'monitor_web', 'dist')   // monitor_web/dist
const OUT = join(here, '..', 'src', 'embedded_assets.h')     // monitor_app/src/embedded_assets.h

// MIME by extension. Unknown → octet-stream. charset only on text types.
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'text/javascript; charset=utf-8',
  '.mjs':  'text/javascript; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map':  'application/json; charset=utf-8',
  '.svg':  'image/svg+xml',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif':  'image/gif',
  '.webp': 'image/webp',
  '.ico':  'image/x-icon',
  '.woff2':'font/woff2',
  '.woff': 'font/woff',
  '.ttf':  'font/ttf',
  '.wasm': 'application/wasm',
  '.txt':  'text/plain; charset=utf-8',
}
const mimeFor = (p) => MIME[extname(p).toLowerCase()] || 'application/octet-stream'

// Recursively collect every file under DIST.
function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) walk(full, acc)
    else acc.push(full)
  }
  return acc
}

let files
try {
  files = walk(DIST).sort()
} catch (e) {
  console.error(`gen_assets: cannot read dist at ${DIST} — run "npm run build" in monitor_web first`)
  process.exit(1)
}
if (files.length === 0) {
  console.error(`gen_assets: dist is empty at ${DIST}`)
  process.exit(1)
}

// Escape a JS string for a C wide-string literal (paths/MIME are ASCII).
const cstr = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')

const parts = []
parts.push(`// AUTO-GENERATED by monitor_app/tools/gen_assets.mjs — DO NOT EDIT.`)
parts.push(`// Source: monitor_web/dist  (${files.length} files)`)
parts.push(`#pragma once`)
parts.push(``)
parts.push(`struct EmbeddedAsset { const char* path; const unsigned char* data; unsigned size; const wchar_t* mime; };`)
parts.push(``)

const table = []
files.forEach((full, i) => {
  const buf = readFileSync(full)
  // web path: dist-relative, POSIX separators, leading slash
  const webPath = '/' + relative(DIST, full).split(sep).join('/')
  const rows = []
  for (let j = 0; j < buf.length; j += 24) {
    rows.push('  ' + Array.from(buf.subarray(j, j + 24)).map((b) => b).join(','))
  }
  parts.push(`static const unsigned char a${i}[] = {`)
  parts.push(rows.join(',\n'))
  parts.push(`};`)
  table.push(`  { "${cstr(webPath)}", a${i}, ${buf.length}u, L"${cstr(mimeFor(webPath))}" }`)
})

parts.push(``)
parts.push(`static const EmbeddedAsset g_embedded_assets[] = {`)
parts.push(table.join(',\n') + ',')
parts.push(`};`)
parts.push(`static const int g_embedded_asset_count = ${files.length};`)
parts.push(``)

writeFileSync(OUT, parts.join('\n'))
const total = files.reduce((n, f) => n + statSync(f).size, 0)
console.log(`gen_assets: embedded ${files.length} files (${(total / 1024).toFixed(1)} KiB) -> src/embedded_assets.h`)
